# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name' : 'Edit/Delete Messages,Notes,Live chat',
    'version' : '14.0.1.0',
    'description': """
    Edit/Delete Messages,Notes,Live chat based on Accessrights
    """,
    'summary': """
        Edit/Delete Messages,Notes,Live chat,
        Edit message,
        Delete message,
        message edit,
        message delete,
        edit note,
        delete note,
        edit all messages,
        delete all messages,
        edit own messages,
        delete own messages,
        edit own notes,
        delete own notes,
        edit live chat,
        delete live chat,
        edit message history,
        edit notes history,
        edit chat history,
        edit accidental message,
        edit accidental notes,
        edit accidental chat,
        accidental chat,
        accidental message edit,
        accidental note edit,
        delete accidental message,
        delete accidental notes,
        delete accidental chat,
        accidental chat delete,
        accidental message delete,
        accidental note delete,
        Chatter,discuss,chat,logs,
        edit,editable,delete,deletable,messages,
        accidental,delete all users messages,
        edit all users messages,
        
	""",
	'author': 'Omax Informatics',
    'category': 'Productivity, Discuss,Message, Note Editing, Message Editing, Note Deleting, Message Deleting',
    'website': 'https://www.omaxinformatics.com',
    'depends' : ['base','mail'],
    'data': [
        'security/edit_message_security.xml',
        'security/ir.model.access.csv',
        'security/delete_message.xml',
        'views/assets.xml',
        'views/custom_message_view.xml',
        'views/mail_message_history.xml',
    ],
    'installable': True,
    'application': True,
    'qweb': [
        'static/src/xml/custom_portal_chatter.xml',
        ],
    'images': ["static/description/banner.png",],
    'currency':'USD',
    'price': 45.0,
    'auto_install': False,
    'live_test_url': 'https://youtu.be/88ZLRx5tnEk',
    'license': 'LGPL-3',
}

